"""empty message

Revision ID: 0752eb2c6492
Revises: da62e1ee387a
Create Date: 2025-03-21 10:40:35.365228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0752eb2c6492'
down_revision = 'da62e1ee387a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tp_items', schema=None) as batch_op:
        batch_op.alter_column('add_time',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tp_items', schema=None) as batch_op:
        batch_op.alter_column('add_time',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
