"""empty message

Revision ID: 09a32ee83fc8
Revises: 4141b62fd57f
Create Date: 2025-07-26 22:37:35.991831

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09a32ee83fc8'
down_revision = '4141b62fd57f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finished_service_buyer', schema=None) as batch_op:
        batch_op.drop_column('finish_time')

    with op.batch_alter_table('service_buyer', schema=None) as batch_op:
        batch_op.drop_column('deal_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_buyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deal_time', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('finished_service_buyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finish_time', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
