"""empty message

Revision ID: 0a49392d150c
Revises: a480c0870578
Create Date: 2025-01-20 12:16:26.527000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a49392d150c'
down_revision = 'a480c0870578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tp_users', schema=None) as batch_op:
        batch_op.alter_column('cooperation_evaluate_score',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tp_users', schema=None) as batch_op:
        batch_op.alter_column('cooperation_evaluate_score',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
