"""empty message

Revision ID: 0b045321fdb2
Revises: 89f3b7f60576
Create Date: 2025-07-26 22:42:25.759526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b045321fdb2'
down_revision = '89f3b7f60576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finished_service_buyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('finish_time')

    with op.batch_alter_table('service_buyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('deal_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_buyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deal_time', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('create_time')

    with op.batch_alter_table('finished_service_buyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finish_time', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('create_time')

    # ### end Alembic commands ###
