"""empty message

Revision ID: 238dc223415d
Revises: 580204bdb737
Create Date: 2025-08-17 22:16:25.533704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238dc223415d'
down_revision = '580204bdb737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_buyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('out_trade_no', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_buyer', schema=None) as batch_op:
        batch_op.drop_column('out_trade_no')

    # ### end Alembic commands ###
