"""empty message

Revision ID: 281831116932
Revises: 8336d2ff43a1
Create Date: 2025-05-17 20:08:59.442063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281831116932'
down_revision = '8336d2ff43a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_category'))
    )
    with op.batch_alter_table('service_pkg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_service_pkg_category_id_service_category'), 'service_category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_pkg', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_service_pkg_category_id_service_category'), type_='foreignkey')
        batch_op.drop_column('category_id')

    op.drop_table('service_category')
    # ### end Alembic commands ###
