"""empty message

Revision ID: 4141b62fd57f
Revises: 2cee714c65d2
Create Date: 2025-07-26 22:35:26.368786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4141b62fd57f'
down_revision = '2cee714c65d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finished_service_buyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finish_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finished_service_buyer', schema=None) as batch_op:
        batch_op.drop_column('finish_time')

    # ### end Alembic commands ###
