"""empty message

Revision ID: 580204bdb737
Revises: 0b045321fdb2
Create Date: 2025-08-02 10:15:32.901145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '580204bdb737'
down_revision = '0b045321fdb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finished_service_buyer')
    with op.batch_alter_table('service_buyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_buyer', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.create_table('finished_service_buyer',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('buyer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('coop_talent_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['tp_users.user_id'], name='fk_finished_service_buyer_buyer_id_tp_users'),
    sa.ForeignKeyConstraint(['service_id'], ['service_pkg.id'], name='fk_finished_service_buyer_service_id_service_pkg'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
