"""empty message

Revision ID: 70064fea6ff4
Revises: 0c025579e80e
Create Date: 2025-05-16 11:32:40.363140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '70064fea6ff4'
down_revision = '0c025579e80e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_buyer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['tp_users.user_id'], name=op.f('fk_service_buyer_buyer_id_tp_users')),
    sa.ForeignKeyConstraint(['service_id'], ['service_pkg.id'], name=op.f('fk_service_buyer_service_id_service_pkg')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_buyer'))
    )
    with op.batch_alter_table('tp_users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tp_users_bought_service_pkg_id_service_pkg', type_='foreignkey')
        batch_op.drop_column('bought_service_pkg_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tp_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bought_service_pkg_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_tp_users_bought_service_pkg_id_service_pkg', 'service_pkg', ['bought_service_pkg_id'], ['id'])

    op.drop_table('service_buyer')
    # ### end Alembic commands ###
