"""empty message

Revision ID: 7db1cbbe97b7
Revises: bfe0408f39f5
Create Date: 2025-07-18 15:20:19.320311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db1cbbe97b7'
down_revision = 'bfe0408f39f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_pkg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intro_img', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_pkg', schema=None) as batch_op:
        batch_op.drop_column('intro_img')

    # ### end Alembic commands ###
