"""empty message

Revision ID: 8336d2ff43a1
Revises: 70064fea6ff4
Create Date: 2025-05-16 12:05:06.774766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8336d2ff43a1'
down_revision = '70064fea6ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_buyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_buyer', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
