"""empty message

Revision ID: 89f3b7f60576
Revises: 09a32ee83fc8
Create Date: 2025-07-26 22:37:48.485095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89f3b7f60576'
down_revision = '09a32ee83fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finished_service_buyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finish_time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('service_buyer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deal_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_buyer', schema=None) as batch_op:
        batch_op.drop_column('deal_time')

    with op.batch_alter_table('finished_service_buyer', schema=None) as batch_op:
        batch_op.drop_column('finish_time')

    # ### end Alembic commands ###
