"""empty message

Revision ID: 961d8c235abf
Revises: 7db1cbbe97b7
Create Date: 2025-07-18 15:42:51.971669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961d8c235abf'
down_revision = '7db1cbbe97b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_pkg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rule_img', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_pkg', schema=None) as batch_op:
        batch_op.drop_column('rule_img')

    # ### end Alembic commands ###
