"""empty message

Revision ID: a480c0870578
Revises: 50aeec084a3a
Create Date: 2025-01-20 12:15:20.494843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a480c0870578'
down_revision = '50aeec084a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tp_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cooperation_evaluate_score', sa.Float(), nullable=True))
        batch_op.drop_column('star_as_business')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tp_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('star_as_business', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('cooperation_evaluate_score')

    # ### end Alembic commands ###
