"""empty message

Revision ID: ad65ed5d6a9a
Revises: 0a49392d150c
Create Date: 2025-01-20 22:33:47.436988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad65ed5d6a9a'
down_revision = '0a49392d150c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tp_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_evaluated', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tp_items', schema=None) as batch_op:
        batch_op.drop_column('is_evaluated')

    # ### end Alembic commands ###
