"""empty message

Revision ID: b7c857e98bec
Revises: d448d2b4c6fb
Create Date: 2025-09-01 21:58:48.870396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7c857e98bec'
down_revision = 'd448d2b4c6fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.BigInteger(), nullable=True))
        batch_op.drop_column('primary_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_id', mysql.BIGINT(), autoincrement=False, nullable=False))
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###
