"""empty message

Revision ID: bf80444713d6
Revises: 238dc223415d
Create Date: 2025-08-18 21:30:38.637525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf80444713d6'
down_revision = '238dc223415d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_files', schema=None) as batch_op:
        batch_op.drop_column('length')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('length', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
