"""empty message

Revision ID: bf9a2745fc86
Revises: dacfd6643c0d
Create Date: 2025-05-18 22:52:50.764234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9a2745fc86'
down_revision = 'dacfd6643c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finished_service_buyer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('coop_talent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['tp_users.user_id'], name=op.f('fk_finished_service_buyer_buyer_id_tp_users')),
    sa.ForeignKeyConstraint(['service_id'], ['service_pkg.id'], name=op.f('fk_finished_service_buyer_service_id_service_pkg')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_finished_service_buyer'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finished_service_buyer')
    # ### end Alembic commands ###
