"""empty message

Revision ID: bfe0408f39f5
Revises: a8760e1fe338
Create Date: 2025-07-18 15:11:52.908276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe0408f39f5'
down_revision = 'a8760e1fe338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_pkg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_img', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_pkg', schema=None) as batch_op:
        batch_op.drop_column('profile_img')

    # ### end Alembic commands ###
