"""empty message

Revision ID: cd5025edd399
Revises: 0752eb2c6492
Create Date: 2025-03-21 10:43:45.041146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd5025edd399'
down_revision = '0752eb2c6492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tp_items', schema=None) as batch_op:
        batch_op.drop_column('is_evaluated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tp_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_evaluated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
